# Generated by Django 4.2 on 2024-12-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=34, unique=True)),
                ('product_name_audio', models.FileField(upload_to='audio/product_name/')),
                ('description_audio', models.FileField(upload_to='audio/description/')),
                ('price_audio', models.FileField(upload_to='audio/price/')),
                ('location_audio', models.FileField(blank=True, null=True, upload_to='audio/location/')),
                ('product_name_text', models.TextField(blank=True, null=True)),
                ('description_text', models.TextField(blank=True, null=True)),
                ('price_text', models.TextField(blank=True, null=True)),
                ('location_text', models.TextField(blank=True, null=True)),
                ('extracted_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_description', models.TextField(blank=True, null=True)),
                ('extracted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_transcription', models.BooleanField(default=True)),
                ('pending_ner', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
