# Generated by Django 4.2 on 2024-12-13 13:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_description_text_product_audio_transcription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="audio_url",
            field=models.FileField(upload_to=core.models.product_audio_upload_to),
        ),
    ]
