# Generated by Django 4.2 on 2024-12-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_product_audio_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="extracted_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
